### ISSUE TITLE
Issue with transport properties of highly repulsive Mie fluids

### ISSUE THREAD

**Issue by gustavochm** [thermotools/KineticGas#25]
Hi! 

First of all thank you for the great work here! 
Second, I have been using the package to compute the transport properties of a range of Mie fluids. I have encountered some problems when computing the viscosity and thermal conductivity of highly repulsive Mie fluids. See the code below, for example.

```
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pykingas.MieKinGas import MieKinGas
import scipy.constants

kb = scipy.constants.Boltzmann
Na = scipy.constants.Avogadro

# defining Mie potential parameters
sigma = 3e-10  # m
eps_by_kb = 150. # K
eps = eps_by_kb * kb
mole_weight = 40. # g/mol
x = np.array([0.5, 0.5])

# To convert between SI units and LJ units
energy_factor = 1 / (eps * Na)  # J/mol -> dim
pressure_factor = sigma**3 / eps  # Pa -> adim
rho_factor = sigma**3 * Na  # mol/m3 -> adim
T_factor = kb / eps  # K -> adim
Tcond_factor = 1. / (kb * np.sqrt(eps/ (mole_weight/1000./Na)) / sigma**2)  # W / m K -> adim
Visc_factor = 1. / (np.sqrt(eps * (mole_weight/1000./Na)) / sigma**2)  # Pa s -> adim
Diff_factor = 1. / (np.sqrt(eps / (mole_weight/1000./Na)) * sigma) # m^2 / s -> adim

# defining the MieKinGas object
la = 6.
lr = 34.

pure_mie = MieKinGas('LJF', mole_weights=[mole_weight], sigma=[sigma],
                     eps_div_k=[eps_by_kb], la=[la], lr=[lr])

# state point to compute in LJ units
Tad = 2.0
rhoad = 0.1

# state point in SI units
rho = rhoad / rho_factor  # mol/m3
V = 1. / rho # m3/mol
T = Tad / T_factor # K

# computing self diffusivity (success)
diff_kinetic = pure_mie.interdiffusion(T, V, x, N=2)
diff_kinetic_ad = diff_kinetic * Diff_factor

# computing viscosity and thermal conductivity (error)
visc_kinetic = pure_mie.viscosity(T, V, x, N=2)
visc_kinetic_ad = visc_kinetic * Visc_factor

tcond_kinetic = pure_mie.thermal_conductivity(T, V, x, N=2)
tcond_kinetic_ad = tcond_kinetic * Tcond_factor
```

For the calculation of the viscosity and thermal conductivity, I got an error that there is inf or NaN as a result of solving a linear system. The self-diffusivity calculation works just fine for the same fluid.

Note that temperature (`T=2.0`) is above the critical temperature for that Mie fluid (lr=34 and la=6). If I change the exponent to something less repulsive (let's say LJ), all properties are computed without any error. 

This was tested for the repo fetched today (17/04/2024). I would appreciate any insights you can provide! Thanks!

Regards,
Gustavo

**Comment by vegardjervell** [comment]
Thank's for letting me know, and thank you for the kind words :)

I've found a fix now and checked that the code runs up to `lr = 100`, though I won't guarantee for the accuracy at those kind of exponents, as there are some correlations in use that are valid only up to about `lr = 50` (I think that's the limit, but we'll have to double check if you want to go there).

I'll do some double checking that everything works as it should with the patch, then I'll merge it.
